[
  {
    "type":"tvshows",
    "name":"示例剧集",
    "poster":"https://example.com/poster.jpg",
    "episodes":[
      {"name":"S01E01","url":"https://.../S01E01.m3u8"},
      {"name":"S01E02","url":"https://.../S01E02.m3u8"}
    ]
  },
  {
    "type":"movies",
    "name":"示例电影",
    "poster":"https://example.com/poster.jpg",
    "url":"https://.../movie.mp4"
  }
]